CREATE TABLE [Turma]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Nome] VARCHAR(10) NOT NULL,
	[Descricao] VARCHAR(50) NOT NULL	
)

CREATE TABLE [Cliente]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Nome] VARCHAR(50) NOT NULL,	
	[Observacao] VARCHAR(100),
	[Saldo] MONEY NOT NULL,
	[TurmaId] UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY ([TurmaId]) REFERENCES [Turma]([Id])
)

CREATE TABLE [Categoria]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Nome] VARCHAR(255) NOT NULL,
	[Descricao] VARCHAR(50) NOT NULL	
)

CREATE TABLE [Produto]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Nome] VARCHAR(255) NOT NULL,
	[Valor] MONEY NOT NULL,
	[CategoriaId] UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY ([CategoriaId]) REFERENCES [Categoria]([Id])
)

CREATE TABLE [Comanda]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[ClienteId] UNIQUEIDENTIFIER NOT NULL,	
	[DataVenda] DATETIME NOT NULL DEFAULT(GETDATE()),
	FOREIGN KEY([ClienteId]) REFERENCES [Cliente]([Id])
)

CREATE TABLE [ItemComanda]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[ComandaId] UNIQUEIDENTIFIER NOT NULL,
	[ProdutoId] UNIQUEIDENTIFIER NOT NULL,
	[Quantidade] INT NOT NULL,
	[Valor] MONEY NOT NULL,
	FOREIGN KEY([ComandaId]) REFERENCES [Comanda]([Id]),
	FOREIGN KEY([ProdutoId]) REFERENCES [Produto]([Id])
)

CREATE TABLE [Login]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Senha] VARCHAR(50) NOT NULL	
)